# .streamlit/config.toml

[theme]
primaryColor = "#27ae60"  # Green
backgroundColor = "#ecf0f1"  # Light Gray
secondaryBackgroundColor = "#d5dbdb"  # Pale Gray
textColor = "#2c3e50"  # Dark Blue-Gray
font = "sans serif"